### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by pascalbros** [igorleonovich/2ndrive#1]
Awesome piece of software!

The correct path for bash profile is:
`~/.bash_profile`

Instead of writing:
Copy local.2ndrive.plist to /Library/LaunchDaemons
Just write:
`sudo cp local.2ndrive.plist /Library/LaunchDaemons/local.2ndrive.plist`

Cheers

**Comment by igorleonovich** [comment]
@pascalbros Thank you very much for the typos and appreciating!

**Comment by igorleonovich** [comment]
@pascalbros I've updated this script and now it is fully automated. Please check it out if you are interested in ;)
